### ISSUE TITLE
TypeError when using bytediff with recursive src

### ISSUE THREAD

**Issue by MrFirthy** [ben-eb/gulp-bytediff#5]
It seems if you use bytediff with a recursive src e.g.

`gulp.src(paths.images.src + '**/*')`

You receive the following error:

`TypeError: Cannot read property 'length' of null`

I think this has something to do with bytediff not being able to find files when an actual extension isn't given, as when I use it in the following format:

`gulp.src([paths.images.src + '**/*.png',paths.images.src + '**/*.jpg',paths.images.src + '**/*.gif',paths.images.src + '**/*.svg'])`

It works correctly.

**Comment by ben-eb** [comment]
Could you post a full stack trace please?

**Comment by MrFirthy** [comment]
Sure:

`
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot read property 'length' of null
    at myprojectdir/www/node_modules/gulp-bytediff/index.js:14:37
    at wrappedMapper (myprojectdir/www/node_modules/gulp-bytediff/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (myprojectdir/www/node_modules/gulp-bytediff/node_modules/map-stream/index.js:96:21)
    at write (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (myprojectdir/www/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
`

**Comment by ben-eb** [comment]
Released as `1.0.0`.

**Comment by MrFirthy** [comment]
Can confirm that this is working for me as of `1.0.0`. Incredibly fast work sir, thank you!

**Comment by ben-eb** [comment]
No problem. :smile:
